# app/api/v1/endpoints/goals.py
from fastapi import APIRouter, Depends, HTTPException, status
from sqlalchemy.orm import Session
from typing import List

from app.db.database import get_db
from app.schemas.goals import GoalCreate, GoalResponse
from app.services.goal_service import GoalService

router = APIRouter()
goal_service = GoalService()

@router.post(
    "/goals/", 
    response_model=GoalResponse,
    status_code=status.HTTP_201_CREATED,
    summary="Create a new goal with AI-generated tasks",
    description="Accepts a vague goal and returns 5 actionable steps generated by AI"
)
async def create_goal(goal: GoalCreate, db: Session = Depends(get_db)):
    try:
        db_goal = goal_service.create_goal_with_tasks(db, goal)
        return db_goal
    except Exception as e:
        raise HTTPException(
            status_code=status.HTTP_500_INTERNAL_SERVER_ERROR,
            detail=f"Failed to process goal: {str(e)}"
        )

@router.get(
    "/goals/{goal_id}",
    response_model=GoalResponse,
    summary="Get goal by ID",
    description="Retrieve a specific goal with its associated tasks"
)
async def get_goal(goal_id: str, db: Session = Depends(get_db)):
    goal = goal_service.get_goal_by_id(db, goal_id)
    if not goal:
        raise HTTPException(
            status_code=status.HTTP_404_NOT_FOUND,
            detail="Goal not found"
        )
    return goal

@router.get(
    "/goals/",
    response_model=List[GoalResponse],
    summary="Get all goals",
    description="Retrieve paginated list of all goals with their tasks"
)
async def get_goals(skip: int = 0, limit: int = 100, db: Session = Depends(get_db)):
    return goal_service.get_all_goals(db, skip, limit)